# Generated by Django 5.1.7 on 2025-03-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.CharField(max_length=200)),
                ('api_key', models.CharField(max_length=50)),
            ],
        ),
    ]
